### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by pigeonsoar** [caterinaurban/Typpete#53]
Why I always get a Segmentation fault even for an empty file when runnig the typpete on Ubuntu 18.04 and Python3.6?

**Comment by caterinaurban** [comment]
It could be a problem with the Z3 version. Which version are you using? We have not updated the tool to the most recent version, yet. Sorry about it!

**Comment by pigeonsoar** [comment]
> It could be a problem with the Z3 version. Which version are you using? We have not updated the tool to the most recent version, yet. Sorry about it!

I use the lastest version(4.8.7), so which version should i use? thank you.

**Comment by caterinaurban** [comment]
The most recent version on which it worked for sure is Z3 version 4.5.1. We will try to get it more up to date as soon as possible!

**Comment by pigeonsoar** [comment]
The problem is solved. Thank you.
